### ISSUE TITLE
unhandledRejection timeout @ Circuit.ts:191:28

### ISSUE THREAD

**Issue by DaxDupont** [CasperTech/node-metaverse#2]
```
You have triggered an unhandledRejection, you may have forgotten to catch a Prom
ise rejection:
Error: Timeout
    at Timeout.timeoutFunc [as _onTimeout] (/home/nodejs/friendComputer/node_mod
ules/@caspertech/node-metaverse/lib/classes/Circuit.ts:191:28)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by Lokomojo** [comment]
Unfortunately there's no way from this message to trace the call which was made. I've added some debug output which will display the message ID being requested, so we can find the culprit when it occurs.
