### ISSUE TITLE
Increased timeouts w/ Node-Metaverse

### ISSUE THREAD

**Issue by IAmNolanPerry** [CasperTech/node-metaverse#78]
I run a bot via this package, and recently, I updated to 0.7.22, and it's giving more issues. The primary is it will connect, but then continue to fail to stay connected, this is shown in several regions, and different datacenters, ruling out Client Side network issues. 
I don't know if this could be a issue with NMV, or with my code. 
```
[2024-05-29 00:23:22]: LOG SL: Connected to Region 
WARNING: Finished reading AvatarAppearanceMessage but we're not at the end of the packet (482 < 585, seq 44)
WARNING: Finished reading AvatarAppearanceMessage but we're not at the end of the packet (482 < 636, seq 50)
Error: Timeout
    at Timeout.<anonymous> (/root/discord-sl-chat-relay/node_modules/@caspertech/node-metaverse/dist/lib/classes/Utils.js:688:28)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[2024-05-29 00:23:47]: ERROR Unhandled rejection: Error: Timeout 
Error: Timeout
    at Timeout.<anonymous> (/root/discord-sl-chat-relay/node_modules/@caspertech/node-metaverse/dist/lib/classes/Utils.js:688:28)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

**Comment by Lokomojo** [comment]
Hey @IAmNolanPerry 

What version were you on before? I'll see if there's been any changes which might trigger that

**Comment by rkoren1** [comment]
i'm also getting timeout error, a bit different one. I'm on a version 0.7.35.  The error is:
```
TimeoutError: Timeout waiting for message of type ParcelDwellReply
    at Timeout.timeoutFunc [as _onTimeout] (C:\inetpub\wwwroot\automatesl\node_modules@caspertech\node-metaverse\lib\classes\Circuit.ts:429:33)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7) {
  timeout: true,
  waitingForMessage: 4294901979
}
```
I'm not sure but i think this happens when regions goes down and then avatar tries to reconnect. Sorry for hijacking this bug, but it might be related.

**Comment by IAmNolanPerry** [comment]
@Lokomojo  this appeared to be a issue that was temporary for about a week and then did not return. I want to chalk it up to something wrong on the SL end maybe?
